### ISSUE TITLE
サブコマンドを間違えたときUsageを表示した方が良くないでしょうか?

### ISSUE THREAD

**Issue by nnabeyang** [zenn-dev/zenn-editor#12]
サブコマンドを間違えたとき

```
😿該当するCLIコマンドが存在しません コマンド一覧は"zenn help"で確認できます
```

と表示されるのですが、もう`zenn help`を実行したときの表示も下に追加した方が良くないでしょうか?
この変更をした場合、現状、`zenn help`に`zenn help`の説明が無いので追加した方が良いかもしれません。

**Comment by catnose99** [comment]
たしかに！
