### ISSUE TITLE
zenn-cliで記事や本のリストを表示したい

### ISSUE THREAD

**Issue by kyoh86** [zenn-dev/zenn-editor#124]
エディタで編集している際などに、slugではなくタイトルの一覧を見れると便利ではないでしょうか。

e.g.

```console
$ zenn list:article
README
code-fence      Code Fence
embed-examples  Embedのテスト
empty
...
```

すでにAPIはあるので、APIを直接叩ける環境には寄与しないと思いますが、CLI経由で呼び出せると少し活用の幅広がるかなと思います。
アイディアとしてはformatも人向けだけではなくエディタとの連携向けにJSONの行リストで吐くなどもあっていいかもしれません。

```console
$ zenn list:article --format json
{"slug":"README"}
{"slug":"code-fence","title":"Code Fence"}
...
```

**Comment by catnose99** [comment]
なるほど、良いですね。PRもありがとうございます。
