### ISSUE TITLE
diffのシンタックスハイライトで、余分な改行が1行入る

### ISSUE THREAD

**Issue by schabibi1** [zenn-dev/zenn-editor#130]
#### 起こっている現象

- diffシンタックスハイライトを使用した際に、余分な改行が1行上に入る

#### 現象が起こった時の記法

```javascript
// diff jsx:src/App.js で指定

import React, { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
-      HEY👋
+      <h1>Counter App 🧮</h1>
+      <button>
+        +
+      </button>
+      <h3>{count} times clicked!🖱</h3>
    </div>
  );
}

export default App;
```

#### 反映結果

![img](https://user-images.githubusercontent.com/25793187/110544687-74059880-812c-11eb-8999-4211f7e412a6.png)

#### 試したこと

- +と-の記述入れ替え
- 前後の余白チェック

**Comment by catnose99** [comment]
ご報告ありがとうございます。確認します

**Comment by schabibi1** [comment]
@catnose99 さん、迅速にお返事くださり、ありがとうございます..！
非常にお世話になっているサービスですので、これからも開発応援しています！
不足している情報がありましたらお知らせください。

**Comment by catnose99** [comment]
@schabibi1 

こちら対応しました。ご報告ありがとうございました。

**Comment by schabibi1** [comment]
@catnose99 
迅速にご対応くださり、ありがとうございます！
