### ISSUE TITLE
n.slug.md形式のチャプターでnが3桁の時プレビューでエラーになる

### ISSUE THREAD

**Issue by lacolaco** [zenn-dev/zenn-editor#135]
表題のとおりです。

![image](https://user-images.githubusercontent.com/1529180/111425963-42498e80-8737-11eb-8fb5-265a5d8eb9fc.png)

![image](https://user-images.githubusercontent.com/1529180/111425689-e1ba5180-8736-11eb-9943-168d924cf370.png)

実際にデプロイすると zenn.dev上では問題なくチャプター順の決定に使われています

![image](https://user-images.githubusercontent.com/1529180/111425923-31008200-8737-11eb-8a35-bed09c129eb9.png)

**Comment by lacolaco** [comment]
https://github.com/zenn-dev/zenn-editor/blob/02bf9b1e245f0b187470f4cdbe80f5fe38656829/packages/zenn-cli/utils/slug-helper.ts#L23

正規表現で1〜2桁となっていますが zenn.dev 上のふるまいとどちらが想定なのでしょうか？

**Comment by catnose99** [comment]
@lacolaco 
こちらzenn.dev 上のふるまいが正しいです。修正します！

**Comment by catnose99** [comment]
対応しました。
お手数ですが`npm install zenn-cli@latest`で更新をお願いします。

**Comment by lacolaco** [comment]
修正対応ありがとうございます！
