### ISSUE TITLE
[機能要望] プレビューのサイドバーを非表示可能にする

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-editor#141]
`zenn preview`でプレビューを表示しながら記事を執筆する際、プレビュー画面のサイドバーを非表示にできると嬉しいです。

機能案としては、ボタンを用意しておいて、表示非表示のトグルができれば良いと考えています。

## actual
<img width="2046" alt="スクリーンショット 2021-04-27 14 25 30" src="https://user-images.githubusercontent.com/20027695/116189883-96975380-a764-11eb-8125-4307281cc69f.png">

## expected
<img width="2037" alt="スクリーンショット 2021-04-27 14 31 51" src="https://user-images.githubusercontent.com/20027695/116190306-5a182780-a765-11eb-9dfa-53d948fa8e8d.png">

**Comment by catnose99** [comment]
しばらくお待ちください。

**Comment by Jxck** [comment]
vscode の Browser Preview で同じことをしようとして同じことを思いました。
@negokaz さんの vscode-zenn-editor がきれいに解決してくれていたので FYI として貼っておきます。
- https://zenn.dev/negokaz/articles/aa4e12b76d516597a00e
- 
それはそれとして非表示オプションについては +1 です。

**Comment by catnose99** [comment]
@korosuke613

こちら対応バージョンをリリースしました。`npm install zenn-cli@latest`で更新をお願いします。

https://github.com/zenn-dev/zenn-editor/pull/151
kazuheさん、ありがとうございました。
