### ISSUE TITLE
Markdown comments is displayed to HTML

### ISSUE THREAD

**Issue by toshi-toma** [zenn-dev/zenn-editor#15]
Thank you for awsome product!!

I'm writing an article via Zenn for the first time.

I write markdown file like this.

```
# title

this is article.

<!-- comment -->

```

Then, I ran `npx zenn preview`. (I'm using zenn-cli@0.1.32)

Zenn display `<p>&lt;!-- comment --&gt;</p>` to HTML.

Does't Zenn support comment block?

**Comment by catnose99** [comment]
Currently Zenn does not support html comment on markdown.
But will think about it.

**Comment by toshi-toma** [comment]
Thanks!!

**Comment by toshi-toma** [comment]
@catnose99 

If enable html option, Is there any problem?

```js
// enable everything
var md = require('markdown-it')({
  html: true,
  linkify: true,
  typographer: true
});
```

https://github.com/markdown-it/markdown-it#init-with-presets-and-options

**Comment by catnose99** [comment]
I guess it might cause XSS.
It's better to use the plugin like this or develop from scratch...
https://github.com/jay-hodgson/markdown-it-inline-comments

**Comment by catnose99** [comment]
@toshi-toma 
Now you can use inline comment `<!-- something -->`!
If you're using zenn-cli, please run `npm run install zenn-cli@latest`.

**Comment by toshi-toma** [comment]
@catnose99 

Awesome!!
Thank you for fix the issue!!
