### ISSUE TITLE
Bug サブコマンドのオプションパースに失敗したとき例外を投げっぱなしにしている

### ISSUE THREAD

**Issue by nnabeyang** [zenn-dev/zenn-editor#17]
サブコマンドのオプションパースに失敗したときの例外がありません。
修正しようかと思いましたが、`arg`が`Error`、`TypeError`と`code`というプロパティ付きの`Error`しか投げないので、
エラーメッセージを日本語化することは出来そうにありませんでした。
cliのオプションパースに使用しているライブラリを考え直した方が良いかもしれません。

これもオプションパースに関連したことなのですが、現状、cliからサブコマンドのオプションを表示する方法が無いように思います。

**Comment by catnose99** [comment]
あーやらなきゃですね。
優先してやらなきゃいけないタスクがかなり溜まっているのでこのあたりの改善は後回しになりそうです。

**Comment by catnose99** [comment]
Shouldn't close this yet.
Command such as `npx zenn preview --foo` still raises an error.
