### ISSUE TITLE
Line wrapping for a line of 100%(-ish) width corrupts following lines

### ISSUE THREAD

**Issue by atsushieno** [zenn-dev/zenn-editor#2]
I am trying to import some markdown drafts to zenn.dev, and noticed that the text editor behavior gets messed after some lines of text.

I figured out that it happens when a line of text goes almost full width on the editor area so that it was (probably) going to wrap the line, but it actually doesn't. The text lines below is an example repro

```
ABC

https://zenn.dev/test?foo=looooooooooooooooooooooooooooooooooooooooooooooong_value

DEF
```

You need certain length of the URL above so that it goes full text area width, but without wrapping.

Once you are done, try to select DEF by SHIFT + right cursor. You cannot select one single character `D`. Instead you'd have `DEF` selected.

Confirmed with Firefox 80.0.1 and <ins>Chrome</ins> Version 85.0.4183.102 (Official Build) (64-bit) on Ubuntu 20.04.

**Comment by catnose99** [comment]
Thank you for the detailed explanation.
It could be a CodeMirror issue, but I'll try to address it.
(The online editor mostly relies on [react-simplemde-editor](https://github.com/RIP21/react-simplemde-editor))

**Comment by atsushieno** [comment]
Thanks for the hints. I think you are most likely correct - https://github.com/codemirror/CodeMirror/issues/4841

**Comment by catnose99** [comment]
That's exactly what I was looking for.

A solution mentioned in the comment below might help me.
https://github.com/codemirror/CodeMirror/issues/4841#issuecomment-317167898

Thanks.

**Comment by catnose99** [comment]
I think this doesn't happen right now.
