### ISSUE TITLE
[bug]: watch option

### ISSUE THREAD

**Issue by isy** [zenn-dev/zenn-editor#21]
previewにwatchオプションが存在しますが、以下のコードによって確実にtrueになるので、オプションの意味がなくなっています

https://github.com/zenn-dev/zenn-editor/blob/3c8aae1160c610efec07b08024f557a0ce072702/packages/zenn-cli/cli/preview/index.ts#L26

cliのオプションでboolean値を直接渡すことはあまりないと思うので、必要であれば `--unwatch` フラグにするなどすると良さそうです

**Comment by catnose99** [comment]
あ、知ってる人だ。
ありがとうございます

直します！

**Comment by catnose99** [comment]
と思ったら動かなかった…
それに`--watch false`とするのは面倒なので`--nowatch`オプションに変更しました。

https://github.com/zenn-dev/zenn-editor/commit/97c91cfa97363474df99f199b56d18f1455e9f24

# ToDo
- [ ] npm releaseしたらドキュメントにオプションについて追記する

**Comment by isy** [comment]
とっても良いもの作ってたので、貢献しちゃいます😎

> ??は
この演算子は左辺が null または undefined の場合に右の値を返すので、--watch falseとすればfalseになると思われです。

おそらくコードを限り、argsのBooleanの使い方が間違ってそうです
これは `--watch` というフラグがあるか判定しているものなので `--watch false`は`true`になります
なので `--watch`のオプションを指定してない場合は null または undefined になってしまい、全て`true`になってしまいます

**Comment by catnose99** [comment]
納得です〜ありがとうございます

**Comment by isy** [comment]
@catnose99 
`--no-watch` オプション追加してもらったもので、バグっぽいものあったので貼っときますー
https://github.com/zenn-dev/zenn-editor/pull/20#discussion_r493652995

**Comment by catnose99** [comment]
あ、直します！
https://github.com/zenn-dev/zenn-editor/issues/23
