### ISSUE TITLE
[機能要望] タイトルの文字数チェックの動作を、WebエディタとCLIで合わせて欲しい

### ISSUE THREAD

**Issue by yuji38kwmt** [zenn-dev/zenn-editor#211]
# 背景
zenn.devのWebエディタで書いた記事をGitHubに移行して、`zenn preview`コマンドでプレビューを表示しました。
タイトルが60文字を超えている記事では、「タイトルは60字以内にしてください」というエラーが表示されます。
![image](https://user-images.githubusercontent.com/6350027/133969124-8dab8f9f-718f-4d75-b860-2dab0bbc73a1.png)

# 要望
zenn.devのWebエディタで書いたときは、このエラーは表示されませんでした。
タイトルの文字数チェックの動作を、WebエディタとCLIで統一して欲しいです。

# 動作環境
* zenn-cli : 0.19.5
* Windows10

**Comment by catnose99** [comment]
ご指摘ありがとうございます。
以前タイトルの最大文字数を60から70に変更した際にCLI側で追従できていませんでした。
次のCLIのアップデートで修正します。
