### ISSUE TITLE
Hard to find the cursor in the dark mode

### ISSUE THREAD

**Issue by KeyAmam** [zenn-dev/zenn-editor#219]
I am not sure if it's the right place to report but it seems hard to find the cursor in the online editor in the dark mode. It would be great if the cursor is a more easy-find color because I am color blind and always use the dark mode. 
Google Chrome: 95.0.4638.69

<img width="974" alt="スクリーンショット 2021-11-07 12 10 14" src="https://user-images.githubusercontent.com/24841453/140630989-f44dbb6f-fb29-4fa1-8002-baff43ad9e53.png">

Thank you for the awesome service! :)

**Comment by catnose99** [comment]
@KeyAmam 
Suppose you are using Chrome force darkmode.
This issue will be fixed in next release.
