### ISSUE TITLE
[bug?] accordion parse

### ISSUE THREAD

**Issue by Ningensei848** [zenn-dev/zenn-editor#227]
アコーディオン（トグル）内で メッセージ を追加しようとすると，パースがミスっている

When I try to add a `message` in an accordion (toggle), the parsing misses:

```md
:::details accordion title

sample text is here.

:::message
this is message
:::

:::
```

![image](https://user-images.githubusercontent.com/20794309/146667803-29e7f6eb-847a-41ac-8479-53b2086dc189.png)

```package.json
  "dependencies": {
    "zenn-cli": "^0.1.100"
  }
```

**Comment by catnose99** [comment]
ありがとうございます。

https://github.com/zenn-dev/zenn-editor/issues/56

リンク先のコメントのように、detailsの方の`:`を1つ増やすことで正しくパースされるようになります。

```
::::details タイトル
本文
:::message
注意事項
:::
::::
```
