### ISSUE TITLE
プレビューモードのときにlocalhost以外からのアクセスも許可したい

### ISSUE THREAD

**Issue by thaim** [zenn-dev/zenn-editor#228]
## 提案内容
`npx zenn preview` でプレビューするときlocalhostからしかアクセスすることができません。
これは、sshして別のサーバ上で開発・記事執筆する場合(自分のユースケース)にプレビューが利用できず不便です。
需要あるか不明ですが、コンテナ化したい場合にも現状ではコンテナ外からアクセスできません。

`--port`オプションで待ち受けポートが変更できるように、`--host`オプションなどを追加してバイディングアドレスを指定できるようにして欲しいです。
具体的には、 `npx zenn preview --host 0.0.0.0` と実行することで、zenn previewを実行しているサーバ外からアクセスしてもプレビュー表示できるようにして欲しいです。

## 実装方法
zenn-cli の `server/lib/server.ts`にてサーバを起動するときに、port引数に加えてhost引数も追加します。

https://github.com/zenn-dev/zenn-editor/blob/f46822c9e3b3716449cc992adf7992d0a58fca49/packages/zenn-cli/src/server/lib/server.ts#L17

## 懸念点
`--open`オプションを同時に指定している場合、どのIPアドレスにアクセスすればよいか不明なので接続エラーになります。
また、プレビュー実行時に標準出力に表示する接続先URLも正しく動作しません。

あくまでバインディングアレスの変更なので、`--open`オプションやプレビュー接続先URLまでは対応しなくてもよいかもしれませんが。

**Comment by uttk-dev** [comment]
@thaim 

こちらのIssue、対応しました！

`npm i zenn-cli@latest` を実行してパッケージを最新にすると、`zenn preview --host xxxx` のような形でホスト名を指定できると思います。

提案していただき、ありがとうございました！
