### ISSUE TITLE
Jekyllの`{{site.baseurl}}`形式のURLでgitリポジトリ内の画像を展開したい

### ISSUE THREAD

**Issue by atsushieno** [zenn-dev/zenn-editor#24]
https://zenn.dev/atsushieno/articles/writing-zenn-content-in-arbitrary-cms に詳しく書いたのですが、Jekyllのホスティングサービスでは（必須かどうかはわかりませんが）`{{site.baseurl}}`という記述があるとそれをURLとして展開するので、これを利用してリポジトリ内の画像を展開できるようになっています。

Zennでもこれが可能だと画像管理が安心してできますし`zenn-user-upload`の利用も少し抑えられるのではないかと思いますがどうでしょうか?

**Comment by catnose99** [comment]
ありがとうございます。
もともと「画像をリポジトリ内で管理してデプロイ時にCloudStorageなどにアップロードする」ことを検討していたのですが、負荷の観点から断念していました。

Jekyllのアイデアはとても参考になりそうですね…。ちょっと調べてみます！

**Comment by catnose99** [comment]
こちらリポジトリで画像を管理できるようになったためクローズします。

https://zenn.dev/zenn/articles/deploy-github-images
