### ISSUE TITLE
[🐛bug] Chapter が 10 個以上になると並び順が崩れる

### ISSUE THREAD

**Issue by su8ru** [zenn-dev/zenn-editor#25]
Chapter が 10 個以上になると並び順がおかしくなってしまいます

`$api.ts と $server.ts の中身` は `10.md` 

| zenn.dev :o: | zenn editor :x: |
| --- | --- |
| ![zenn.dev](https://user-images.githubusercontent.com/33474143/94184508-f5e76980-fede-11ea-8304-587860663992.png) | ![image](https://user-images.githubusercontent.com/33474143/94184548-08fa3980-fedf-11ea-88c2-e77112fc3174.png) |

**Comment by catnose99** [comment]
分かりやすい報告ありがとうございます！🙏
確認します！

**Comment by catnose99** [comment]
@su8ru 
こちらさきほど修正しました。
お手数をおかけしてすみませんが`npm install zenn-cli@latest`で更新をお願いします。

**Comment by su8ru** [comment]
こちらこそありがとうございます、修正確認できました！

これからも頑張ってください！
