### ISSUE TITLE
`:hoge:`記法で絵文字を表示したい

### ISSUE THREAD

**Issue by 4513ECHO** [zenn-dev/zenn-editor#251]
現在、[Qiita](https://qiita.com/Qiita/items/c686397e4a0f4f11683d#%E7%B5%B5%E6%96%87%E5%AD%97)/GitHubでは絵文字を`:hoge:`のような記法で書くことができますが、Zennでは対応されていません。よろしければ対応のほどよろしくお願いいたします。

**Comment by cm-igarashi-ryosuke** [comment]
検討の結果、ニーズが限定的であり実装コストに見合わないため対応しないこととなりました。

**Comment by 4513ECHO** [comment]
了解しました。
