### ISSUE TITLE
印刷時に details を開いて欲しい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#267]
印刷して読む場合に details が close なため summary しか印刷されません。

できれば open にする方法が欲しいです。

**Comment by catnose99** [comment]
ご指摘ありがとうございます。
[onbeforeprint](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint)を使って対応できないか検討してみます。

**Comment by uttk-dev** [comment]
@Jxck 

こちらアプリ側( zenn.dev )で対応しましたので、クローズさせて頂きます。
もしライブラリ側( zenn-cli )での対応を希望されていた場合は、お手数ですがその旨を教えて頂ければと思います。

注意点として、アプリ側のキャッシュが残っている場合がありますので、有効にならない場合は一旦キャッシュを削除して再度試して頂ければ有効になるかと思います。

よろしくお願いします。

**Comment by Jxck** [comment]
@uttk-dev ご対応ありがとうございます。

> もしライブラリ側( zenn-cli )での対応を希望されていた場合
すいません、ライブラリでもほしいです。

というか、 zenn.dev 上での印刷だとサイドバーが隠せないので、印刷には不向きだと思っていました。
確かに、 zenn.dev 上では details が開いているようなので、下が実現すると助かります。

- zenn-cli でローカル印刷時にも details が消える
- zenn.dev 上の印刷時にサイドバーが隠せる

後者は別 issue にしておきます。

**Comment by uttk-dev** [comment]
@Jxck 
ありがとうございます。
対応まで少し時間がかかるかも知れませんが、お待ち頂ければと思います。

一応確認ですが、

>・zenn-cli でローカル印刷時にも details が消える

というのは、「 印刷時に details を開く 」という認識で大丈夫ですか？

**Comment by Jxck** [comment]
間違えました 「details を開く」です。
