### ISSUE TITLE
`:::message` のセマンティクス

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#273]
拡張記法の [`:::message`](https://zenn.dev/zenn/articles/markdown-guide#%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8) ですが、以下のような HTML に変換されています。

```html
<div class="msg ">
<p>メッセージをここに</p>
</div>
```

```html
<div class="msg alert">
<p>警告メッセージをここに</p>
</div>
```

ここには、 `class` が付与して見た目を変えるためだけの拡張になっており、 HTML コンテンツ上は "メッセージ記法" / "アラート記法" が使われていることすらわかりません。せっかく HTML での文書作成に特化しているので、ここにも HTML としてよりリッチなセマンティクスの付与を検討してみてはどうでしょうか？

非常に近い参考実装として、 web.dev にも似た機能があります。

- https://web.dev/handbook/web-dev-components/#asides

こちらでは、 `<div>` ではなく [`<aside>`](https://developer.mozilla.org/ja/docs/Web/HTML/Element/aside) が使われています。`<aside>` は聖杯レイアウトの左右に使うものと思われがちですが、 ARIA でいう [complementary role](https://developer.mozilla.org/ja/docs/Web/Accessibility/ARIA/Roles/Complementary_role) にあたるので、この用途もおかしくはないと思います。

仮に `<div>` を `<aside>` にしただけだと、「メッセージである」「アラートである」という意図が伝わらないので、追加で何か欲しいところです。ちなみに後者を `role=alert` にすると、この目的とは変わってしまうと思うので、お勧めしません。
こういうとき「困ったら素直に書く」というのが一つの手段だと思います。 web.dev の場合は骨組みだけ取り出すとこんな感じです。

```html
<aside>
  <span>
    <svg aria-label="Error sign" role="img">...</svg>
  </span>
  <strong>Caution</strong>
  <p>Use the caution aside to indicate a potential pitfall or complication.</p>
</aside>
```

Zenn の今の実装は、文字の前のアイコンをスタイルとみなし、 `::before` に対して `content: "!"` を付与しており、これがメッセージもアラートも同じで色だけ違うという実装です。この実装を極力変えたくないのであれば、 Alternative Text を付与することも一応できます。

```css
content: "!" / "message"
content: "!" / "alert"
```

ただ、対応しているブラウザがまだ少なく、 Safari はこれがついてると無視するし、ちょっと使いにくいです。

なので、このマークを消えても良い背景ではなく、意図を示すためのコンテンツ(web.dev でいう "Caution" って書いちゃう代わり)と捉えて、これを `<img>` や `<svg>` に SVG で HTML 中に埋め込み、そこに `aria-label` や `alt` などを付与するという手もあると思います。もっとシンプルに、アラート記法の方は `<strong>` を使う、だけでもいいかもしれません。

以上はあくまで例で、「 "メッセージ記法" / "アラート記法" をどういう用途のために実装するか」という視点が最も重要になるので、あくまで参考として、チームで議論いただければと思います。

**Comment by tannerjohn65** [comment]
本件、ご指摘と詳細な情報提供いただきありがとうございます。
現状は他の実施事項の兼ね合いがあるため、将来的に実施させていただきます！
