### ISSUE TITLE
[bug?] メッセージ内にコードブロックがあるとスタイルが崩れる

### ISSUE THREAD

**Issue by su8ru** [zenn-dev/zenn-editor#281]
![image](https://user-images.githubusercontent.com/33474143/160222740-69dd4566-bfcd-4fc7-ab01-c33f7f55dbe1.png)

`:::message` 内にコードブロックがある場合、

- X 方向のスクロールが機能しない（際限なく grow）
- 左上のアイコンが表示されない（shirnk されている）

といった現象が発生します。

zenn.dev 上で発見し、zenn-cli@0.1.108 で再現を確認しました。

<details>
<summary>
サンプルに用いた markdown
</summary>
<br />
<pre>
:::message
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```
:::
:::message
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
:::
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```
</pre>
</details>

**Comment by uttk-dev** [comment]
@su8ru 

ご報告ありがとございます。
こちら #279 で対応済みですが、zenn のリリースが間に合っておらず、まだ反映されていません。
近日リリースされると思いますので、 それまでお待ちいただければと思います。

**Comment by su8ru** [comment]
Community の Issue は確認していませんでした…！
ありがとうございます、お手数おかけし申し訳ありません！
