### ISSUE TITLE
Monorepoの構成を見直す

### ISSUE THREAD

**Issue by uttk-dev** [zenn-dev/zenn-editor#289]
## 概要

~~zenn-editor ではモノリポ環境を構築するために、[lerna](https://github.com/lerna/lerna) を使用していますが、
先日、[公式のREADMEに今後メンテナスされない旨が追記されました。](https://github.com/lerna/lerna/pull/3092)~~

~~そのため、非常に心苦しいですが、この Issue で lerna の代替案を模索したいと思います。~~

Monorepo の構成を、この Issue で見直したいと思います。

見直す理由:

- yarn workspace と lerna で役割が被っているところがある
  - そのせいで、どのツールを使えばいいか迷うことがある
- lerna のビルドが遅いのと、もう少し色々と機能が欲しい
  - tuborepo や Nx はビルドを上手くやってくれていたはず
- lerna の機能をあまり使えていない
  - ほとんど publish する時だけ使ってる
  - publish だけなら [lerna-lite](https://github.com/ghiscoding/lerna-lite) を使うのもあり
- なるべくなら yarn workspace に寄せたい
  - 設定など少なく済む
  - コマンドが分かりやすい

**Comment by Karibash** [comment]
Lernaは現在[Nx](https://github.com/nrwl/nx)の開発元である[Nrwl](https://nrwl.io/)が管理を引き継いでいます。
https://github.com/lerna/lerna/issues/3121

下記のPRにてREADMEも更新されています。
https://github.com/lerna/lerna/pull/3124/files

**Comment by uttk-dev** [comment]
ありがとうございます。
構成の見直しは必要なため、タイトルと概要の内容を変更させて頂きました。
