### ISSUE TITLE
コードブロック内の Scheme コードのインデントがずれる

### ISSUE THREAD

**Issue by noriok** [zenn-dev/zenn-editor#29]
コードブロック内の Scheme コードのインデントがずれてしまいます。

```scheme
(let ((a 1)
      (b 2))
  (+ a b))
```

表示結果(`(a 1)` と `(b 2)` が縦にそろっていない):
![let](https://user-images.githubusercontent.com/1705960/94348884-d5ecad00-007a-11eb-9514-93a096da8817.png)

**Comment by catnose99** [comment]
こちら最新のzenn-cliおよびzenn.devで修正しました。
（word-spacingというCSSプロパティが影響していたみたいです）
お手数ですが、`npm install zenn-cli@latest`でアップデートをお願いします。
