### ISSUE TITLE
[Proposal] Disable `break` of markdown-it

### ISSUE THREAD

**Issue by ulwlu** [zenn-dev/zenn-editor#290]
## 概要

- Zennで明示的に指定している、markdown-itのbreakをdisableする

https://github.com/zenn-dev/zenn-editor/blob/3a70b090029c5fd204ce8e8deb7778d18e7e5ded/packages/zenn-markdown-html/src/index.ts#L24

## なぜか

- 「ファイル内では改行したいが、実際のweb上の表示では改行したくない」ケースで、マークダウン執筆時に見づらくなる
- markdownlintの[MD013](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md013---line-length) に対応できずignoreするか、web上で改行が増えることを許容しなければならない

前提としてmarkdownのspecificationは `A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines.` と記載されており、空白行を挟まなければ改行と扱われません。

この上でmarkdown-itのbreakオプションは、markdownに慣れていないユーザーの混乱を避けるなどのUX性のためにenableされる事があります。
例えばgithubのREADME.mdなどのマークダウンファイルはデフォルトの仕様通り空白行を挟まなければweb上でも改行されませんが、githubのissueではmarkdown記法であるにも関わらず空白行を挟まなくてもweb上で改行されて表示されます。
この違いは直接markdownファイルを管理するか、web上で簡易的に書くかの違いによる感覚差と思っています。README.mdはローカルにmdファイルが存在して、markdownlintやprettierの範囲対象としたいケースなどで仕様に厳密になるべきですが、issueはwebのguiからしかいじらないという違いです。

この例のように、Zennの現在の仕様は「Github連携しておらずweb上から投稿している人の中で、markdownの本来の仕様よりも改行したらそのまま改行してくれる現在の仕様になれている」人にとってはメリットがあると思います。
一方で、ローカルでmdファイルを書きたい私個人の観点としては、disableにして頂いた方がファイル管理の面で嬉しく感じますし、慣れている本来の仕様通りにかけて嬉しいです。

## デメリット

1: 「Github連携しておらずweb上から投稿している人の中で、markdownの本来の仕様よりも改行したらそのまま改行してくれる現在の仕様になれている」人は混乱する

2: これまで下記のようにmarkdown-itのbreakに依存して記載していた記事は、改行がなくなります。

```
下記の記事を参考にしてください。
[hoge](hoge)

# これが

下記の記事を参考にしてください。 [hoge](hoge)

# こう表示されてしまう
```

そのためbreaking-changeになります。

**Comment by tannerjohn65** [comment]
お世話になっております。本件、ご要望いただきありがとうございます！
具体的な情報や影響についての情報をいただき大変助かります！　今回いただいた内容については、ご提示いただいたようにメリット/デメリットの両方の観点から検討が必要なため、チームで慎重に検討させていただきます。
引き続き、何卒よろしくお願いいたします。

**Comment by catnose99** [comment]
@ulwlu 
丁寧なご提案をありがとうございます。

GitHubが`.md`ファイルとissue上のmarkdownで改行の仕様が異なることには気づきませんでした。

> この違いは直接markdownファイルを管理するか、web上で簡易的に書くかの違いによる感覚差と思っています。README.mdはローカルにmdファイルが存在して、markdownlintやprettierの範囲対象としたいケースなどで仕様に厳密になるべきですが、issueはwebのguiからしかいじらないという違いです。

こちら物凄く腑に落ちました。個人的にも同意見です。

Zennの場合、GitHubから同期したmarkdownをWebのエディターからも編集したいというニーズが大きく、markdownに関する仕様は統一したいと考えています。また、すでに作成済みの投稿に対する影響を考えると、現時点では対応する方針を立てることが難しそうです。

的を得たご提案にも関わらず、ご要望に添った仕様にできておらず心苦しく思います。大変申し訳ないですがご理解いただけますと幸いです。

**Comment by ulwlu** [comment]
御二方ともご確認下さりありがとうございました。承知致しました。
