### ISSUE TITLE
zenn-embed-elementsが導入できない

### ISSUE THREAD

**Issue by oshanQQ** [zenn-dev/zenn-editor#293]
はじめまして。
Zennという素晴らしいプロダクトをメンテナンスしてくださって、ありがとうございます。

現在、Next.jsとTypeScriptで組んだブログにzennのmarkdown cssを導入しようとしています。
この際、`READEME.md`どおりに`zenn-embed-elements`を導入しようとしてもエラーを吐かれてしまいます。

ソースコードはこちらです。
```tsx
import { AppProps } from "next/app";
import "../styles/index.css";
import { useEffect } from "react";
import initTwitterScriptInner from "zenn-embed-elements/lib/init-twitter-script-inner"; // ここでエラー

export default function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    import("zenn-embed-elements");
  }, []);
  return (
    <>
      <script
        dangerouslySetInnerHTML={{
          __html: initTwitterScriptInner,
        }}
      />
      <Component {...pageProps} />
    </>
  );
}
```

エラーメッセージは次の通りです。
```
モジュール 'zenn-embed-elements/lib/init-twitter-script-inner' またはそれに対応する型宣言が見つかりません。ts(2307)
```

私が確認した範囲でも、エラー同様`zenn-embed-elements`の実装に`init-twitter-script-inner`は見当たらなかったです。

こちらの件について伺いたくIssueを作成させていただきました。
確認していただけると幸いです。

**Comment by catnose99** [comment]
ありがとうございます。

こちらzenn.devでの埋め込みのパフォーマンスを上げるため、またGitHubのソースコードの埋め込みを実現するために、最近埋め込みの仕組みを根本的に見直しました。今後新しい埋め込みに関するコードもオープンソースにしたいと考えていますが、もうしばらく時間がかかりそうです。

お手数ですが、`zenn-markdown-html`や`zenn-content-css`、`zenn-embed-elements`といったパッケージについては`v0.1.106`をお使いいただけると幸いです。
（現状zenn.devでのリリース効率を優先しており、セマンティックなバージョニングができておらずすみません）

ご不便をおかけしてすみませんが、よろしくお願いします。

**Comment by oshanQQ** [comment]
ありがとうございます！

そうだったんですね。私の方もZennの現状把握を怠っておりました。

ご指摘の通り、今回はバージョンを調整して利用させていださきます。

**Comment by catnose99** [comment]
新しい埋め込みコンテンツのオープンソース化についてはまだ準備中ですが、最新バージョンのzenn-editorを組み込むことができるようにドキュメントを更新しました。

https://github.com/zenn-dev/zenn-editor#readme
