### ISSUE TITLE
[機能要望] 記事のプレビューに目次を表示してほしい

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-editor#297]
zenn.dev では記事ページに目次が表示されます。
Zenn CLIによる記事のプレビュー画面には目次が表示されないため、目次の見え方を確認したい場合に不便です。

Zenn CLIによる記事のプレビュー時も同じような目次が表示されてほしいです。

**Comment by tannerjohn65** [comment]
ご意見いただきありがとうございます。　
Zenn CLIでも目次が確認できた方が確かに執筆しやすいと思うので、今後対応したいと存じます。
実施時期については、他の機能追加や実施事項との兼ね合いがあるため検討させてください。
引き続き、よろしくお願いいたします！

**Comment by korosuke613** [comment]
ご対応ありがとうございました！
https://github.com/zenn-dev/zenn-editor/pull/456
