### ISSUE TITLE
[bug?(zenn-cli)] throw `Cannot find module 'node:process'` on node v14.17.6

### ISSUE THREAD

**Issue by MH4GF** [zenn-dev/zenn-editor#308]
# 起きている事象
zenn-cliをlatestにアップグレードし `zenn preview` を実行すると、以下のエラーが発生します。

```bash
❯ yarn dev            
yarn run v1.22.19
$ zenn preview
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- /app/node_modules/zenn-cli/dist/server/zenn.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /app/node_modules/zenn-cli/dist/server/zenn.js:3:2223938
    at /app/text-output-content/node_modules/zenn-cli/dist/server/zenn.js:3:2310989
    at Object.<anonymous> (/app/node_modules/zenn-cli/dist/server/zenn.js:3:2310993)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/zenn-cli/dist/server/zenn.js'
  ]
}
```

previewだけでなく、 `new:article` 等のCLIのコマンドも同様のエラーで終了します。
アップグレード前のバージョンは0.1.98, アップグレード後は0.1.113です。
https://github.com/MH4GF/text-output-content/commit/b46cc05631c87b9d0422040d5d8002bf316e2e8d

# Workaround

この問題はnodeのバージョンがv16.13.0以降、v14であればv14.18.0以降であれば発生しません。
ref: https://stackoverflow.com/questions/71473345/whats-the-difference-between-nodeprocess-and-process

まだ詳しく調べきれていないのですが、zenn-cliのソースコードを軽く見たかぎりでは `node:<package_name>` でimportしている箇所は見つけられなかったため、なぜこのエラーが出るのだろう…？となっています。
0.1.98では動作するため、その間のdiffにリグレッションがあるのかもしれません。

もしくは、package.jsonで指定しているenginesを引き上げる解決策もあるかもしれません。
https://github.com/zenn-dev/zenn-editor/blob/971e649d1e340e30c0f4eb0b2e9b195ee28ca9da/packages/zenn-cli/package.json?plain=1#L102

**Comment by uttk-dev** [comment]
@MH4GF 

詳細な報告ありがとうございます🙇‍♂️
こちらでも再現できたので、近々対応したいと思います。

>まだ詳しく調べきれていないのですが、zenn-cliのソースコードを軽く見たかぎりでは node:<package_name> でimportしている箇所は見つけられなかったため、なぜこのエラーが出るのだろう…？となっています。

私の方で調べたところ、依存パッケージに ESModule を使用したモノがあり、そのパッケージが原因となっているようです。
そのため、zenn-cli のソースコード自体に今回のバグの要因は無いと思われます。

**Comment by uttk-dev** [comment]
@MH4GF 

`zenn-cli@0.1.114` で対応しましたので、こちらのissueをクローズさせて頂きたいと思います。

修正に伴って、サポートする node.js のバージョンを `>=14.0.0` にしましたので、
それより前のバージョンを使用していた場合は、お手数ですが node.js のアップデートをして対応してもらえればと思います。

よろしくお願いします。

**Comment by MH4GF** [comment]
迅速な対応をありがとうございました😊
