### ISSUE TITLE
エラーメッセージ中のリンクタグがそのまま表示されている。

### ISSUE THREAD

**Issue by ooooooo-q** [zenn-dev/zenn-editor#31]
v0.1.36にて`components/ErrorRow.tsx`で表示されるエラーメッセージについてもHTMLエスケープがされるようになったため、エラーメッセージ中にあったリンクタグがそのまま出力されるようになってしまったようです。

↓は記事の`type`に適当な値を入れたときのものです。

<img width="750" alt="error link" src="https://user-images.githubusercontent.com/395584/94352353-dd25b200-009e-11eb-9dcc-2d6a18684f70.png">

**Comment by catnose99** [comment]
あー…ありがとうございます。メッセージごとにエスケープすることにします！
