### ISSUE TITLE
Emoji 14.0 を記事のアイキャッチ絵文字に指定するとエラーメッセージが表示される

### ISSUE THREAD

**Issue by korosuke613** [zenn-dev/zenn-editor#318]
https://github.com/zenn-dev/zenn-community/issues/418#issuecomment-1200608337 にて、GitHub 連携における記事のアイキャッチ絵文字に Emoji 14.0 を利用できるようになりました。

しかし、Emoji 14.0 を指定した Markdown を zenn-cli でプレビューすると、「絵文字（emoji）を1つだけ指定してください」というエラーメッセージが表示されてしまいます。（🫠 [1FAE0](https://unicode.org/emoji/charts-14.0/emoji-released.html#1fae0)）

<img width="860" alt="スクリーンショット 2022-08-03 12 38 44" src="https://user-images.githubusercontent.com/20027695/182518960-0c4e6f17-6655-40b1-9cd3-bf53ce65f947.png">

zenn-cli version: 0.1.115

**Comment by cm-wada-yusuke** [comment]
@korosuke613 
いただいたプルリクを反映したバージョンがリリースされました。

`yarn add zenn-editor@latest` として `v0.116` がインストールされることをご確認ください。対応ありがとうございました。

**Comment by korosuke613** [comment]
@cm-wada-yusuke 
最新版でエラーが消えることを確認しました。
ありがとうございました🥳
