### ISSUE TITLE
Docswell（ドクセル）のスライドを埋め込めるようにしたい

### ISSUE THREAD

**Issue by yamat47** [zenn-dev/zenn-editor#321]
[Docswell](https://www.docswell.com/) に登録されたスライドを埋め込めるようにしたいです。
JavaScript を使った埋め込み機能があるので、それを内部で呼び出せるようにしたいです。

**Comment by cm-igarashi-ryosuke** [comment]
@yamat47 RP作成までご対応いただきありがとうございます。導入可否について開発チームで検討させていただきます。

**Comment by cm-igarashi-ryosuke** [comment]
関連: https://github.com/zenn-dev/zenn-community/issues/409

**Comment by cm-igarashi-ryosuke** [comment]
現時点の結論をこちらにも記載しておきます。

https://github.com/zenn-dev/zenn-editor/pull/322#issuecomment-1207859880

> 埋め込み対象のページによってアスペクト比が異なるので、自前でスクリプトを書いてiframe内のページのアスペクト比を取得する必要があります。実装を加えるとなるとメンテナンスのコストもかかってきますので、対応するかどうかは今後のシェアを見ながら慎重に判断したいと考えております。

**Comment by tannerjohn65** [comment]
本件、起票いただきありがとうございます！　チームで改めて議論いたしましたが、今後埋め込みを可能とする際には網羅的な方法など含めて改めて検討したいと思います。そのため、このIssueはクローズさせていただきます。
PR作成いただいたにも関わらず申し訳ございません。。。　引き続き、よろしくお願いいたします。

**Comment by ku-suke** [comment]
ドクセルの中のものです。
本件、ドクセル側でもアスペクト比を保った形でのスライドプレーヤを検討しておりますが、現状はSlideshareのようにpadding-bottomハックを活用いただく形で対応できないでしょうか。

```
.embed-slideshare {
    padding-bottom: calc(56.25% + 38px);
    position: relative;
    width: 100%;
    height: 0;
}

.embed-slideshare iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border: none;
}
```

あるいは、埋め込み用JS `https://www.docswell.com/assets/libs/docswell-embed/docswell-embed.min.js` のホワイトリスト化による許可をいただけるのであれば、将来的な変更も含めより安定してご提供可能かと思われます。ご検討よろしくお願いいたします。

**Comment by cm-dyoshikawa** [comment]
本件、Zennチームを再検討を行い、昨日実装・リリースさせていただきました。

https://info.zenn.dev/2024-09-18-embed-docswell-slides

みなさんの提案と貢献に感謝いたします。ありがとうございました！

@yamat47 2022年のPRでは誠にありがとうございました。
参考にさせていただいた実装が多く、当時のcommitをcherry-pickさせて頂こうと思ったのですが、

- 元のブランチが削除されているためか、cherry-pickで参照できなかったこと
- 当時よりファイル構成に変更があり、そのまま実装を持ってくることが難しかったこと
- 今回の再検討にあたり仕様の変化があったこと

から、commitを含めることを断念し、上記リリースノートにて貢献を紹介させていただくことにしております。 🙇 

引き続きZennをよろしくお願いいたします。

**Comment by yamat47** [comment]
@cm-dyoshikawa 

わざわざありがとうございます！

方針や対応内容など、まったく異論ありません。
リリースされて嬉しいです、いつも開発をありがとうございます！
