### ISSUE TITLE
when use zenn-markdown-html in Vite it won't work

### ISSUE THREAD

**Issue by kitiho** [zenn-dev/zenn-editor#328]
Error: Module "crypto" has been externalized for browser compatibility. Cannot access "crypto.randomBytes" in client code.
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/51785099/184833527-b68d3b23-09cf-4289-8b0d-a3f540b92314.png">

because of using 'crypto', I changed the source code by replacing it with 'crypto-random-string', it works well.

**Comment by cm-wada-yusuke** [comment]
@kitiho Hi, can you share your reproduce repo? We want to make sure the zenn-markdown-html  used as expected.

**Comment by kitiho** [comment]
> @kitiho Hi, can you share your reproduce repo? We want to make sure the zenn-markdown-html used as expected.

Hi, here's the [demo](https://stackblitz.com/edit/vitejs-vite-nn9v7e?file=src%2FApp.vue,vite.config.js,package.json&terminal=dev),  and in **vite.config.js** I've already do pre-bundling.
```js
optimizeDeps: {
    include: ['zenn-markdown-html'],
  }
```
And I've made a [pr](https://github.com/zenn-dev/zenn-editor/pull/329), hope it helps~

**Comment by cm-wada-yusuke** [comment]
@kitiho Thanks for providing the sample. Our zenn-markdown-html is designed to run in Node.js and is intended for use with server-side rendering. So even if you use Vue, please use it in combination with `createSSRApp`. if you use it with SSR, vite should automatically recognize the build for node.js and the build for SPA. If you still get errors when building with SSR, I'm glad to report them again.

**Comment by kitiho** [comment]
@cm-wada-yusuke Thanks for your reply. 了解です。昨日zenn-cliのコードを見てから、server-sideで実行すべきことがわか理ました。今はzenn-markdown-htmlのコードからViteのプラグインに変換して使用しています。とりあえず、ありがとうございます。
