### ISSUE TITLE
アコーディオンの <summary> 内マークアップ

### ISSUE THREAD

**Issue by toyboot4e** [zenn-dev/zenn-editor#332]
機能リクエストです。アコーディオンの `<summary>` タグ内をマークアップできますか。

[現在の実装らしき箇所](https://github.com/zenn-dev/zenn-editor/blob/2db7785470bd407a1c2dad98695001eefed2fdee/packages/zenn-markdown-html/src/utils/md-container.ts#L21)

# 例

```md
:::details `AstIdMap` の定義

dummy text

:::
```

## 現在の表示

`<summary>` タグ内のマークアップがありません (zenn scrap):

<img width="207" alt="details-1" src="https://user-images.githubusercontent.com/47905926/185730027-b93d3765-38e0-4bed-8b6c-ddf642a201af.png">

## 理想的な表示

`<summary>` タグ内に `<code>`, `<bold>` などのインラインスタイル (？) が適用されると大変嬉しいです:

<img width="150" alt="details-2" src="https://user-images.githubusercontent.com/47905926/185730030-1b2dd52b-dc44-4ca7-86c8-0160d655a6b7.png">

よろしくお願いします。

**Comment by uttk-dev** [comment]
@toyboot4e 

Issue の作成ありがとうございます。
まだ対応するかは分かりませんが、検討させて頂きたいと思います。
同じような提案が https://github.com/zenn-dev/zenn-community/issues/135 で既に提案されているため、管理しやすくするためにこの Issue はクローズさせて頂きたいと思います。
