### ISSUE TITLE
Jest のバージョンを上げる

### ISSUE THREAD

**Issue by uttk-dev** [zenn-dev/zenn-editor#336]
## 概要

いま使っている jest のバージョンでは package.json の exports フィールドや ESModule を解決できないため、色々と無理している部分がある。そこを jest のバージョンを上げることで解決したい

## TODO

- jest のバージョンを最新にする 
  - v27 → v28 には破壊的変更が含まれるので更新する際は注意( [参考](https://jestjs.io/docs/upgrading-to-jest28) )

**Comment by catnose99** [comment]
vitestへの置き換えの機運があるため一旦クローズ
