### ISSUE TITLE
zenn-cli の React のバージョンを上げる

### ISSUE THREAD

**Issue by uttk-dev** [zenn-dev/zenn-editor#337]
## 概要

現在、zenn-cli の React のバージョンは v17 なので v18 以上にしたい。
しかし、React v18 では色々と変更が多いため更新する際は、他のライブラリも含めて更新する。

## TODO

- React のバージョンを v18 以降にする
  - それに伴い tsconfig.json の見直し
- 使っているReact 関連ライブラリのアップデート
  - Material UI : v4 → v5 以降にしたい

**Comment by cm-wada-yusuke** [comment]
MUIはアイコンにのみ利用していたため外しました。
React18へのバージョンアップは引き続き検討します。
