### ISSUE TITLE
 ✍️  が使用できない emoji ?

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#40]
以下のようなエラーが出ており、本文で絵文字を使用してないので、ヘッダのものが使えないように見えます。
🤔 などに変えてみるとエラーが消えるのですが、 ✍️ がだめな理由はなんでしょうか？
単純にポリシーならそれでよいのですが、ぱっとマニュアルなどがでてこなかったので、もしどこかに理由が書かれていたら、エラーメッセージにリンクなどがあると嬉しいです。そうでなければバグかもしれないと思ったので立てます。

![image](https://user-images.githubusercontent.com/322289/95031937-869a2280-06f3-11eb-85e6-705ac208ee22.png)

**Comment by Jxck** [comment]
ためしに無視してデプロイしプレビューしてみたら普通に見れたので、やっぱりエラーメッセージ側のバグに見える？

![image](https://user-images.githubusercontent.com/322289/95032771-b991e580-06f6-11eb-8d03-32dff8c18d34.png)

**Comment by catnose99** [comment]
@Jxck 
絵文字の正規表現にミスがありました。
v0.1.43で修正しましたので、お手数をおかけしてすみませんが`npm install zenn-cli@latest`でアップデートをお願いします。
