### ISSUE TITLE
Zenn コンテンツの型情報を `zenn-validator` に実装した後、名称を変更する

### ISSUE THREAD

**Issue by uttk-dev** [zenn-dev/zenn-editor#402]
## 概要

パッケージの利便性を高めるために `zenn-validator` に型情報を寄せる形で実装することになりました。
それに伴い、 `zenn-validator` の役割が多くなってしまうため、名称を変更する必要があります。

## 候補

- ~~`zenn-model`~~
- ~~`zenn-schema`~~

~~他に良い案があれば、コメントで提案よろしくお願いします。~~

**`zenn-model` に決定しました🎉**

## 関連

https://github.com/zenn-dev/zenn-community/issues/480

**Comment by cm-wada-yusuke** [comment]
- `zenn-markdown-base`
- `zenn-base`
- `zenn-types`

とかもアリですね。MaterialUIからパクりました。
https://github.com/mui/material-ui/tree/master/packages

**Comment by azarashi2931** [comment]
Zenn として article や book を内包する概念を何と呼んでいるのかわかりませんが、`zenn-validator` が今後もそこだけをスコープとするパッケージであり続けるならそれを表す単語を入れた方がよいと思います。
例えば、「article や book を内包する概念」を「コンテンツ」と呼ぶなら以下のような名前が良いと思います。(最後の単語はここまでのコメントの案から取りました)

 - `zenn-contents-model` 
 - `zenn-contents-types`

**Comment by azarashi2931** [comment]
型定義を移動するだけの PR を作成しました。レビューよろしくお願いします！

- #404 
- #405

**Comment by uttk-dev** [comment]
みなさん、ありがとうございます。チームで話し合った結果、`zenn-model` に決定しました 🎉
