### ISSUE TITLE
[機能要望] Toc に h1, h2 くらいまでは欲しい。

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#41]
book の左にある Toc がチャプターレベルで並んでいるのですが、できれば見出し (h1, h2 までなど) の Toc もあると、分量ある本を書いたときに読みやすいかと思いました。チャプター以下のアコーディオンでも良いかもしれません。

![image](https://user-images.githubusercontent.com/322289/95032081-2bb4fb00-06f4-11eb-9b96-8f0b2ba87c55.png)

**Comment by catnose99** [comment]
ありがとうございます。読み手の体験を考えると仰る通りだと思うので対応を検討します。
（現在の構成上やや難易度が高く、時間がかかるかもしれません）

※ アプリ側の機能になるので、issueを別ページに移動させていただきました。
https://github.com/zenn-dev/zenn-roadmap/issues/109
