### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by isamu** [zenn-dev/zenn-editor#414]
package.jsonには
 ```
 "license": "MIT"
 ```
とありますが、README.mdには
```
Licence
非営利目的の利用のみ許可します。
```
とあります。どちらの表記が正しいのでしょうか？

**Comment by isamu** [comment]
以下のnpmのページでは「非営利目的の利用のみ許可します。」はなく、MITとなっています。
https://www.npmjs.com/package/zenn-markdown-html

**Comment by cm-igarashi-ryosuke** [comment]
@isamu ご指摘ありがとうございます。整理しますのでしばらくお時間をください。

**Comment by cm-igarashi-ryosuke** [comment]
@isamu お待たせしました。整理が完了しましたのでお知らせします。

- リポジトリのライセンスはMITです。
- 「非営利目的の利用のみ許可します。」については、[こちら](https://github.com/zenn-dev/zenn-editor/tree/canary/packages/zenn-markdown-html#zenndev-%E3%81%A8%E5%90%8C%E3%81%98%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF%E8%A6%81%E7%B4%A0%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B)に詳細を記載しております。

簡単に背景を説明しますと、いままではzenn-markdown-htmlの中に、Zennの非公開の埋め込みサーバーのホストがハードコードされていました。それを無尽蔵に利用されては困るので「非営利目的の利用のみ許可します。」としていました。現在は、サーバーのホストはオプションで設定するように変更されています。

**Comment by isamu** [comment]
確認ありがとうございます。
明確になりました。
