### ISSUE TITLE
デフォルト設定をしたい

### ISSUE THREAD

**Issue by uga-rosa** [zenn-dev/zenn-editor#438]
new:article ではオプションで Front Matter を指定できますが、これのデフォルト設定が欲しいです。
事前に設定しておけば、単に `npx zenn new:article` とするだけで毎回決まった絵文字を使う、といったことが出来るようになってほしいです。

**Comment by uttk-dev** [comment]
@uga-rosa 

提案ありがとうございます。`alias` などを使用することで対応できないですかね？

```shell
$ alias zna="npx zenn new:article --emoji 😸"
$ zna

created: articles/8e2110197ec6ef.md
```

**Comment by cm-wada-yusuke** [comment]
package.json にスクリプトを書くことでも実現できます。

```json
  "scripts": {
    "preinstall": "npx only-allow pnpm",
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "textlint",
    "lint-staged": "lint-staged",
    "watch": "watch \"make build\" ./book_awsxangular/src",
    "new:article": "zenn new:article --emoji 📝"         <---------------------------- 
  },
```

記事をつくるとき：

```sh
npm run new:article -- --slug twitter-api-migration
```

**Comment by kyoh86** [comment]
+1

すでに他の方から例示されてるとおり、package.jsonのスクリプトで対応できますし、そうしてきたんですが、

- たまに記事を書こうとする
- zennのマニュアルを見返す
- `npx zenn new:article` だな、よしよし
- 絵文字指定するの忘れた
- どうせならデフォで絵文字を指定したい…そうだ！package.jsonのスクリプトで…
- →すでに用意されてることに気づく

という一連の流れをすでに何回かやってるので、できればデフォルト値を設定で持てると嬉しい気持ちは若干ばかりあります。（無理にとは言いません）

**Comment by uga-rosa** [comment]
今回の目的に関して、現状でも十分対応できることは分かりました。ありがとうございます。
このissueは閉じることにします。
