### ISSUE TITLE
preview を起動すると cover.png が古いファイルになる

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#44]
現象だけ言うと

1. cover.png を更新して push してデプロイ
2. そのあと zenn-cli で preview をローカルに起動
3. すると何故か cover.png が古いのに戻る

なぜかわからないけどそういう現象が手元で起きてます。
もうすこし詳細がつかめたら追記します。

**Comment by catnose99** [comment]
ご報告ありがとうございます。
古いのに戻るのはローカル上で、デプロイされたカバー画像（zenn.dev上の画像）は最新のものになっているという認識で良いでしょうか？

**Comment by Jxck** [comment]
そうです、ローカルで preview を起動するとcover.png に差分が生まれ古くなってることに気づきました。毎回 git ck で差分を消してから作業するようにしてる状況です。(一回差分ごとコミットしてデプロイしてしまったので revert したりしましたが)

**Comment by catnose99** [comment]
ありがとうございます。確認します。

**Comment by Jxck** [comment]
すいません、これはこちらのビルドフローのバグでした。お騒がせしました。

**Comment by catnose99** [comment]
あ、そうだったのですね！丁寧にご報告いただき、ありがとうございました。
