### ISSUE TITLE
プロジェクトのルートからzenn-cliを起動できるnpm scriptsが欲しい

### ISSUE THREAD

**Issue by steelydylan** [zenn-dev/zenn-editor#441]
もしかしたら方法があるのかもしれませんが、すぐにzenn-cliが起動できずに苦労しました。
もしかするとルートから起動できるコマンドがnpm scriptsにあると確認が楽かもしれません

**Comment by tannerjohn65** [comment]
本件、ご確認いただきありがとうございます。
ルートからコマンドを実行する場合、以下のように実施いただくと実行が可能です。
```
$ pnpm --filter={package名} {実行したいコマンド}
```
現状、上記の方法で対応可能であるため、こちらのIssueはクローズさせていただきます！
引き続き、よろしくお願いいたします。
