### ISSUE TITLE
[機能要望] コードブロックへの外部ファイル読み込み

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#46]
サンプルコードが多い本を書く時、例えば JS のコードを埋め込むなら .js ファイルで書いて埋め込めると、エディタのモードも分けられるし、個別に実行やテスト、リントができるので便利です。(むしろ無いと辛い)

そこで、デプロイしたディレクトリから以下のような記法で読み込んで表示してくれると嬉しいです。

````
```js:./sample/1_1_hello.js
# 言語指定の後ろにパスが指定された場合はそのファイルが埋め込まれる
```
````

**Comment by catnose99** [comment]
バックエンドでの対応が思いのほか難しそうなので、ローカルで埋め込み状態をプレビューできつつ、プッシュする前にビルド（というか結合したマークダウンファイルを生成）する方向でいけないか考えてみます。

**Comment by Jxck** [comment]
この件ですが、以下の対応でカバーできそうです。

https://zenn.dev/zenn/articles/markdown-guide#github

ありがとうございます！(close かどうかは任せます)

**Comment by tannerjohn65** [comment]
ご確認いただきありがとうございます！　こちらCloseさせていただきます！！
