### ISSUE TITLE
jsfiddleのembedの表示のデフォルトタブを変更したい

### ISSUE THREAD

**Issue by maiko-ando** [zenn-dev/zenn-editor#471]
[現行のmarkdown記法で挿入したjsfiddle](https://zenn.dev/zenn/articles/markdown-guide#jsfiddle)のembedされた結果の表示について、デフォルトのタブを設定することができないため、jsfiddleのembeddingのパラメータを設定できるようにしたいです。

https://docs.jsfiddle.net/embedding-fiddles

**Comment by cm-igarashi-ryosuke** [comment]
ご提案ありがとうございます！確認しますので少々お時間をください。

**Comment by cm-igarashi-ryosuke** [comment]
@maiko-ando 埋め込みパラメータの設定ができることを確認しました。指定方法をドキュメントに追記しましたのでお試しください。
https://zenn.dev/zenn/articles/markdown-guide#jsfiddle

**Comment by maiko-ando** [comment]
@cm-igarashi-ryosuke 
ドキュメントへの追記のご対応ありがとうございました！
jsfiddleを埋め込んでいた当該記事にて、提示いただいた方法で動作することを確認致しました

迅速なご対応に重ねお礼申し上げます、有難うございました！！
本件こちらにてcloseさせていただきます
