### ISSUE TITLE
codesandboxのembed時の処理or表示エラーが不適切

### ISSUE THREAD

**Issue by GunseiKPaseri** [zenn-dev/zenn-editor#490]
# 概要
codesandboxは`@[codesandbox](https://codesandbox.io/embed/～)`の形で入力することで埋め込むことができる。
この時`～`の部分で`+`記号は許容されておらず、含まれている場合には`「https://codesandbox.io/embed/」から始まる正しいURLを入力してください`と表示されてしまう。

https://github.com/zenn-dev/zenn-editor/blob/05f5ab84362423d862c1ae72947e713a7f47ccb8/packages/zenn-markdown-html/src/utils/url-matcher.ts#L35

codesandboxで埋め込みiframeを生成する際、Layoutは「Editor + Preview」「Editor」「Preview」から選ぶことができるが、「Editor + Preview」を選ぶと`view=Editor+%2B+Preview`というオプションがついてしまい、これを埋め込むことができない。

## 提案
- `+`を除くように提案するエラーメッセージを出す
  - これをするとpreviewとeditorの併用ができなくなる
- `+`を許容する

**Comment by cm-igarashi-ryosuke** [comment]
@GunseiKPaseri ご提案ありがとうございます。問題なさそうなので `+` を許容する方向で修正しようと思います。

ただ、zenn.devのレイアウトでは幅が小さいため「Editor + Preview」を選択したとしても「Editor」が隠れてしまうようでした。

**Comment by cm-igarashi-ryosuke** [comment]
@GunseiKPaseri こちら対応完了いたしました。zenn-cli をお使いの場合は、最新バージョンにアップデートしてご利用ください。
