### ISSUE TITLE
[提案]: Prettier の全面的な導入

### ISSUE THREAD

**Issue by senkenn** [zenn-dev/zenn-editor#501]
現在 .vscode/settings.json 等にフォーマッタの設定がないのでソースの体裁が各所で異なるところが散見されます。
Prettier などを導入したほうが良いと思いました。

追記：settings.json もそうだが、zenn-cli でしか活用できていないので各パッケージでも使用できるようにする

**Comment by cm-igarashi-ryosuke** [comment]
確かに、 prettier の設定ファイルはルートにありますが、 packages/zenn-cli しか prettier を活用していないようですね。
対応したいと思います 🙇

**Comment by cm-igarashi-ryosuke** [comment]
@senkenn
チームのタスク優先度的に後回しになりそうです。

どなたでもコントリビュート可能ですので、よろしければお願いします。
