### ISSUE TITLE
ローカルのサーバーが立ち上がらない

### ISSUE THREAD

**Issue by mmmommm** [zenn-dev/zenn-editor#51]
ここで聞いていいのか分からないですが、困っているのでお願いします。

手元で動かそうと思ったのですが
<img width="1177" alt="スクリーンショット 2020-10-21 20 17 34" src="https://user-images.githubusercontent.com/51479834/96712714-7d3ed480-13da-11eb-8394-4a87e286368a.png">
このようなエラーが出て立ち上げができないです。

zenn-editor/packages/zenn-cli　以下でも試したのですが、`postcss-import`、`postcss-url`、`autoprefixer`がないなどのエラーが出て全て追加した後に上記と同じ

` true is not a PostCSS plugin`のエラーが出ました。

https://github.com/vercel/next.js/issues/17236
調べたらこの記事が出てきたのでバージョンの変更等を行ったのですが、動かず。

よろしければサーバーの立ち上げ方について教えていただきたいです。

**Comment by catnose99** [comment]
導入手順は下記の記事の通りに行っていますか？
https://zenn.dev/zenn/articles/install-zenn-cli


下記のステップでサーバーを立ち上げます。
1. `npm install zenn-cli`（初回のみ）
2. `npx zenn init`（初回のみ）
3. `npx zenn preview`（サーバーを起動）

スクショを見る限り、buildを行っているような気がしますが、buildは不要です。

**Comment by mmmommm** [comment]
紛らわしくてすいません、zenn-cliのプレビューをしたいのではなくて、このzenn-editorのリポジトリをforkして手元で動かしたいという意味です。
