### ISSUE TITLE
コンテナネスト時に最初の終了フェンスで親コンテナも終了してしまう

### ISSUE THREAD

**Issue by arcage** [zenn-dev/zenn-editor#56]
details コンテナ内に message　コンテナを置こうとして以下のような記述をすると、message コンテナの終了を示す1つ目の `...\n` で details コンテナも終了してしまい、二つ目の `...\n` が本文として溢れ出てしまうようです。

```
:::details タイトル
本文
:::message
注意事項
:::
:::
```

今回のように、内側のコンテナが外側のコンテナの最後に来る場合は、2つ目の `...\n` を削れば想定した表示になるのですが、このような使用方法で問題ないでしょうか。

**Comment by catnose99** [comment]
@arcage 

こんな感じで親側の方の`:`を4つにすればネストできると思います。
```
::::details タイトル
本文
:::message
注意事項
:::
::::
```
よろしくお願いします！
