### ISSUE TITLE
URL を URL のまま表示する方法

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#58]
https://zenn.dev/zenn/articles/markdown-guide#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AE%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF

URL が必ずカードになり、過去以下のように表示していたものを修正する必要が出ました。

### before
![image](https://user-images.githubusercontent.com/322289/98545369-baf79480-22d8-11eb-942b-7108891256e1.png)

### after
![image](https://user-images.githubusercontent.com/322289/98545400-c6e35680-22d8-11eb-9a20-71b53abbcf8f.png)

URL を URL のまま表示する方法(opt-out する方法)が何か欲しいです。この例ではコードブロックでもいいかもしれませんが、カードではなく単なるリンクで良い場合もあると思うので、カードを表示の方が opt-in でできると良いようにも思います。

**Comment by Jxck** [comment]
今の所 workaround としてはこうか。

![image](https://user-images.githubusercontent.com/322289/98546033-b2538e00-22d9-11eb-95e6-3ab55d0ffd7b.png)

まあ、これでも良いと言えば良いのですが、、

**Comment by catnose99** [comment]
修正が必要になったとのこと、大変申し訳ありませんでした。

カード表示の方をopt-inでできるようにすることも検討したのですが、

- マークダウンのポータビリティを保つためにZenn独自の記法を増やしたくない
- 独自記法だとリンクを気軽に貼れない（面倒で使われない）

などの理由からURL単体の場合はデフォルトでカード表示することにしています。

今のところのworkaroundのひとつがリストを使うことになりますが、もう少し明確な方法を用意することを検討します。

**Comment by Jxck** [comment]
ちなみに、こういう変更に早く気づくにはどこを見ておけばいいんですかね？
zenn の記事の更新だと気づきにくいので subscribe できる何かが欲しいです。

**Comment by catnose99** [comment]
そうですよね。
Twitterで更新情報は流していますが、他のツイートで埋もれるため変更を把握するには微妙です。
RSSフィードで購読できるChangelogを作り、Breaking changeがあった場合にも分かりやすくしようと思います。

**Comment by catnose99** [comment]
https://github.com/zenn-dev/zenn-roadmap/issues/157

**Comment by catnose99** [comment]
@Jxck 
Changelogページを作りました。
https://zenn.dev/changelog

**Comment by Jxck** [comment]
早い！ありがとうございます！

**Comment by Jxck** [comment]
元の URL についてはリストで解消できることと、自分以外にユースケース持ってる人がいない気もするので、一旦 close します。
