### ISSUE TITLE
削除した本の slug の再利用

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-editor#59]
下書きの整理のために以下を行いました。

1. 本(下書き)を作成し deploy
2. 整理のために一旦 zenn 上で削除
3. 再度デプロイ

すると、以下のエラーでデプロイできなくなってしまいました。

> book（xxx）の更新に失敗しました（Slugは既に使用されています。） 

書籍の URL には著者の名前が入るので、 slug が早いものがちということもなさそうなため、少なくとも下書きなら大丈夫だろうと思ったのですが、一度 zenn 上で削除した本の slug はもう使いまわせないのでしょうか？
(その slug が使えないと困るので戻したいです)

**Comment by catnose99** [comment]
本の削除については安全のためにバッチ処理しているため、完全に削除されるまでに時間がかかっていました。
さきほどこの処理を見直したため、削除した本のスラッグでも使えるようになっていると思います。

ちなみに1度でも購入された本は、購入者が引き続き閲覧できるようにレコードが残るため、（退会などにより）削除してもスラッグの再利用はできません。

URL上はユーザー名とスラッグが含まれていますが、内部的な都合で、他のユーザーの本も含めてスラッグはユニークである必要があります。
（チャプターはスラッグがひとつの本の中でユニークであればOKです）
不便かとは思いますがご理解いただければ幸いです。

**Comment by Jxck** [comment]
ありがとうございます、デプロイできました！

> ちなみに1度でも購入された本は、購入者が引き続き閲覧できるようにレコードが残るため、（退会などにより）削除してもスラッグの再利用はできません。

わかります、それでいいと思います。

> URL上はユーザー名とスラッグが含まれていますが、内部的な都合で、他のユーザーの本も含めてスラッグはユニークである必要があります。

なんと、 slug は早いものがちだったんですね、、これは盲点でした。
普及すると取り合いになるので名前空間がユーザで切れてると良さそうですが、了解です。

**Comment by catnose99** [comment]
slugの早いもの勝ちはあまり良くないと思うので、今後どこかのタイミングでユーザーというスコープ内にユニークしたいと思っています。
そうすればslugの最低文字数の制限も撤廃できますし。

よろしくお願いします。
