### ISSUE TITLE
アップデートの通知がおかしい

### ISSUE THREAD

**Issue by mmmommm** [zenn-dev/zenn-editor#77]
# 概要
プレビューモードから`ctrl + C`したときのアップデートのバージョン通知がおかしかったです。

<img width="544" alt="スクリーンショット 2020-12-13 19 27 40" src="https://user-images.githubusercontent.com/51479834/102010347-e3aff580-3d80-11eb-9420-a6cfe50c8059.png">

再現できるのがおそらくこの通知が出る時だけなので大きな問題ではなくupdate-notifier側の問題かもしれないですが、一応報告しておきます。

**Comment by catnose99** [comment]
ありがとうございます。確認してみます。
