### ISSUE TITLE
[要望]helpの出し方に一貫性が無いので統一されていてほしい

### ISSUE THREAD

**Issue by kuuote** [zenn-dev/zenn-editor#79]
# 概要
`zenn`コマンド自体はhelpを出すのに`zenn help`のようにハイフン無しのサブコマンドを利用するのに対し、サブコマンドは`zenn <subcommand> --help`のようにハイフン有りのオプションになっており混乱してしまうので、統一された方法もしくは別のやり方が欲しいです。

# 提案
個人的には`zenn`コマンド自体も`--help`を受け付けるようにする方法と、Goのツールチェーンの様に`zenn help <subcommand>`でサブコマンドのhelpが出る方法のどちらかでどうだろうかと思っています。

**Comment by catnose99** [comment]
あ、仰る通りですね。「zennコマンド自体も--helpを受け付ける」ようにしようと思います。
