### ISSUE TITLE
ホットリロードを繰り返す度にイベント数が増え続ける

### ISSUE THREAD

**Issue by nnabeyang** [zenn-dev/zenn-editor#8]
何度かホットリロードを繰り返すと次のようなエラーメッセージがターミナルに表示されます。

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 all listeners added. Use emitter.setMaxListeners() to increase limit
```

おかしいと思い、コードを確認しましたが`cli/preview/index.ts`内の`watcher.on`で毎回イベントが追加され続けている
ようでした。`watcher.once`にすると増えなくなりました。

**Comment by catnose99** [comment]
なるほど！こちら修正します。
ありがとうございます！

**Comment by catnose99** [comment]
修正済み
https://github.com/zenn-dev/zenn-editor/commit/05434137c1187c013a49d2220dac370bc7dc1134

@nnabeyang 
READMEにお名前を記載させていただきました。何か不都合がありましたらお知らせください

**Comment by nnabeyang** [comment]
@catnose99 

ありがとうございます。

一応、こんな感じにすれば直るかなと思ってました。プロジェクト内の全ファイル監視するより、パターン指定のほうが軽そうだなぁという考えです。バグあるかもしれないですが。
```
  if (watch) {
    const watcher = chokidar.watch(`${process.cwd()}/{articles,books}/**/*`);
    const io = socketIo(server);
    watcher.on("ready", () => {
      io.on("connection", (socket) => {
        watcher.once("all", async () => {
          socket.emit("reload");
        });
      });
    });
  }
```

**Comment by catnose99** [comment]
おぉ、ありがとうございます！
ご指摘のポイントも修正させていだきます！
