### ISSUE TITLE
プログラミング言語ごとのdiff

### ISSUE THREAD

**Issue by pandaman64** [zenn-dev/zenn-editor#86]
prismjsでは各プログラミング言語用のハイライトとdiffのハイライト両方を適用することができるようです．
https://prismjs.com/plugins/diff-highlight/

Zennでこれを利用できるとプログラムの差分の表示が見やすくなって嬉しいです．

**Comment by catnose99** [comment]
The syntax described on PR below doesn't work...
https://github.com/PrismJS/prism/pull/1889

```
Prism.highlight(code, Prism.languages.diff, 'diff-' + diffLanguage)
```
