### ISSUE TITLE
記事をAndroidでみると太字が効いていない場合がある

### ISSUE THREAD

**Issue by sogaoh** [zenn-dev/zenn-editor#92]
https://twitter.com/ngoktanio/status/1346429762739130368
の指摘を見たので確認してみたところ、自分のとある記事で現象を確認できました。

記事 :  https://zenn.dev/sogaoh/articles/20-12-17-f76cea4051692f0ba7bb

スクリーンショット :  https://twitter.com/sogaoh/status/1346436821866057728

指摘の方の機種は Pixel 3 、自分のは Redmi で、ブラウザは共に Chrome です。

**Comment by kkiyama117** [comment]
念の為スクリーンショットも 貼っておきます.

- PC
(google chrome 87.0.4280.88, manjaro linux 20.2)

![Screenshot from 2021-01-05 23-04-52](https://user-images.githubusercontent.com/27989936/103655521-bda9f980-4faa-11eb-9814-45b075d9f281.png)

- Pixel2 (emulator)

![Screenshot from 2021-01-05 23-06-44](https://user-images.githubusercontent.com/27989936/103655574-cc90ac00-4faa-11eb-9f15-bed088e0fcf0.png)

- `znc` class の strong の 設定をoffにした場合

![Screenshot from 2021-01-05 23-06-57](https://user-images.githubusercontent.com/27989936/103655578-ce5a6f80-4faa-11eb-8e74-1f12e4750e16.png)

**Comment by kkiyama117** [comment]
@catnose99 

少し挙動を調べてみたのですが、CSSそのものの問題というよりfontとの噛み合わせの問題で、手元の環境だと
`zenn-content-css/src/_content.scss` の L7の値が

- `600` -> 日本語は細字(normal), 英字は太字
- `700` -> 日本語も英語も太字

になりました.　当方Linux環境で `Rendered Fonts` が `Droid Sans Japanese` になっていますが、ここら辺はFont依存かと思います. 故にPull Requestを出すのは見送らせていただきますが、この辺りが影響しているのは間違いないかと思います。

**Comment by catnose99** [comment]
確認したところ、仰る通り、端末内のフォントによって`font-weight: 600`が対応していなかったようです。さきほど修正しました
@sogaoh 
@kkiyama117 
ご指摘と調査までしていただき、ありがとうございました。
